# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import equity_pb2 as equity__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in equity_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EquityCalculatorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculateHandVsRandomEquity = channel.unary_unary(
                '/EquityCalculatorService/CalculateHandVsRandomEquity',
                request_serializer=equity__pb2.HandVsRandomEquityRequest.SerializeToString,
                response_deserializer=equity__pb2.SingleEquityResponse.FromString,
                _registered_method=True)
        self.CalculateHandVsHandEquity = channel.unary_unary(
                '/EquityCalculatorService/CalculateHandVsHandEquity',
                request_serializer=equity__pb2.HandVsHandEquityRequest.SerializeToString,
                response_deserializer=equity__pb2.SingleEquityResponse.FromString,
                _registered_method=True)
        self.CalculateHandVsRangeEquity = channel.unary_unary(
                '/EquityCalculatorService/CalculateHandVsRangeEquity',
                request_serializer=equity__pb2.HandVsRangeEquityRequest.SerializeToString,
                response_deserializer=equity__pb2.SingleEquityResponse.FromString,
                _registered_method=True)
        self.GenerateRangeHeatmap = channel.unary_unary(
                '/EquityCalculatorService/GenerateRangeHeatmap',
                request_serializer=equity__pb2.RangeHeatmapRequest.SerializeToString,
                response_deserializer=equity__pb2.HeatmapResponse.FromString,
                _registered_method=True)
        self.GenerateHandVsRangeHeatmap = channel.unary_unary(
                '/EquityCalculatorService/GenerateHandVsRangeHeatmap',
                request_serializer=equity__pb2.HandVsRangeHeatmapRequest.SerializeToString,
                response_deserializer=equity__pb2.HeatmapResponse.FromString,
                _registered_method=True)


class EquityCalculatorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CalculateHandVsRandomEquity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateHandVsHandEquity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateHandVsRangeEquity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateRangeHeatmap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateHandVsRangeHeatmap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EquityCalculatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculateHandVsRandomEquity': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateHandVsRandomEquity,
                    request_deserializer=equity__pb2.HandVsRandomEquityRequest.FromString,
                    response_serializer=equity__pb2.SingleEquityResponse.SerializeToString,
            ),
            'CalculateHandVsHandEquity': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateHandVsHandEquity,
                    request_deserializer=equity__pb2.HandVsHandEquityRequest.FromString,
                    response_serializer=equity__pb2.SingleEquityResponse.SerializeToString,
            ),
            'CalculateHandVsRangeEquity': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateHandVsRangeEquity,
                    request_deserializer=equity__pb2.HandVsRangeEquityRequest.FromString,
                    response_serializer=equity__pb2.SingleEquityResponse.SerializeToString,
            ),
            'GenerateRangeHeatmap': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateRangeHeatmap,
                    request_deserializer=equity__pb2.RangeHeatmapRequest.FromString,
                    response_serializer=equity__pb2.HeatmapResponse.SerializeToString,
            ),
            'GenerateHandVsRangeHeatmap': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateHandVsRangeHeatmap,
                    request_deserializer=equity__pb2.HandVsRangeHeatmapRequest.FromString,
                    response_serializer=equity__pb2.HeatmapResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'EquityCalculatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('EquityCalculatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EquityCalculatorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CalculateHandVsRandomEquity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EquityCalculatorService/CalculateHandVsRandomEquity',
            equity__pb2.HandVsRandomEquityRequest.SerializeToString,
            equity__pb2.SingleEquityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateHandVsHandEquity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EquityCalculatorService/CalculateHandVsHandEquity',
            equity__pb2.HandVsHandEquityRequest.SerializeToString,
            equity__pb2.SingleEquityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateHandVsRangeEquity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EquityCalculatorService/CalculateHandVsRangeEquity',
            equity__pb2.HandVsRangeEquityRequest.SerializeToString,
            equity__pb2.SingleEquityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateRangeHeatmap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EquityCalculatorService/GenerateRangeHeatmap',
            equity__pb2.RangeHeatmapRequest.SerializeToString,
            equity__pb2.HeatmapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateHandVsRangeHeatmap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EquityCalculatorService/GenerateHandVsRangeHeatmap',
            equity__pb2.HandVsRangeHeatmapRequest.SerializeToString,
            equity__pb2.HeatmapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
